HousingProject/Controllers/CRMController.cs
using HousingProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using HousingProject.Enum;

namespace HousingProject.Controllers
{
    public class CRMController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            var opportunity = db.Opportunities.Include(x => x.Buyer).ToList();
            return View(opportunity);
        }

        public ActionResult Contacts()
        {
            var contacts = db.CustomerContacts.Include(x => x.buyers).ToList();
            return View(contacts);
        }
        
        public ActionResult Customers()
        {
            var customer = db.BuyerDetails.ToList();
            return View(customer);
        }
    }
}

HousingProject/Controllers/DetailsController.cs
using HousingProject.Data;
using HousingProject.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;

namespace HousingProject.Controllers
{
    public class DetailsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Details
        public ActionResult Index(int BuyerId)
        {
            return View();
        }
        public ActionResult ProceedLead(int id, int oppoId,string type)
        {
            var leads = db.BuyerDetails.Include(x => x.Contacts).Include(x => x.Opportunities).Include(x => x.DocumentUploadeds).Where(x => x.BuyerId == id).FirstOrDefault();
            ManageBuyerViewModel manager = new ManageBuyerViewModel();
            manager.BuyerDetail.BuyerId = leads.BuyerId;
            manager.BuyerDetail.BuyerName = leads.BuyerName;
            manager.BuyerDetail.Email = leads.Email;
            manager.BuyerDetail.MobileNo = leads.MobileNo;
            manager.BuyerDetail.DateOfBirth = leads.dob;
            manager.BuyerDetail.FatherFirstName = leads.FatherFirstName;
            manager.BuyerDetail.FatherMiddleName = leads.FatherMiddleName;
            if(oppoId == 0)
            {
                manager.Opportunities = leads.Opportunities.ToList();
            }
            else
            {
                var leadStatus = leads.Opportunities.Where(x => x.Id == oppoId).Select(x => x.OpportunityStatus).FirstOrDefault();
                manager.BuyerDetail.LeadStatusId = Convert.ToInt32(leadStatus);
                manager.BuyerDetail.OpportunityId = oppoId;
            }
            manager.FileUpload = leads.DocumentUploadeds.ToList();

            manager.Type = type;
            return View(manager);
        }

        [HttpPost]
        public JsonResult SetStatus(int BuyerId,int OpportunityId, int status)
        {
            var buyer = db.Opportunities.Where(x => x.BuyerId == BuyerId && x.Id == OpportunityId).FirstOrDefault();
            buyer.OpportunityStatus = status;
            db.SaveChanges();
            return Json(new { status = "OK", currentStatus = status });
        }

        [HttpPost]
        public JsonResult SaveDetails(BuyerDetailViewModel model)
        {
            var buyerDetail = db.BuyerDetails.Find(model.BuyerId);
            buyerDetail.FatherFirstName = model.FatherFirstName;
            buyerDetail.FatherMiddleName = model.FatherMiddleName;
            buyerDetail.Email = model.Email;
            buyerDetail.dob = model.DateOfBirth;
            buyerDetail.MobileNo = model.MobileNo;
            db.SaveChanges();
            return Json(new { status = "OK", result = model });
        }

        [HttpPost]
        public ActionResult UploadLeadFiles()
        {
            //var file = Request.Files["FileUpload"];
            int BuyerId = Convert.ToInt32(Request.Form["BuyerId"]);

            bool SavedSuccessfully = true;
            string fName = "";
            foreach (string filename in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[filename];
                var guid = Request.Form["Guid" + filename.Last()];
                fName = file.FileName;
                if (file != null && file.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Files/" + guid));
                    string pathstring = Path.Combine(path.ToString());

                    bool isexist = Directory.Exists(pathstring);
                    if (!isexist)
                    {
                        Directory.CreateDirectory(pathstring);
                    }
                    string uploadpath = string.Format("{0}\\{1}", pathstring, fName);
                    file.SaveAs(uploadpath);
                    var docDetail = new DocumentUploaded
                    {
                        BuyerId = BuyerId,
                        FileName = guid + "/" + fName,
                    };
                    db.DocumentUploadeds.Add(docDetail);
                }
            }
            db.SaveChanges();
            if (SavedSuccessfully)
            {
                return Json(new { status = "OK" });
            }
            return Json(new { status = "False" });
        }

        [HttpPost]
        public JsonResult DeleteFile(string filename)
        {
            try
            {
                var findDoc = db.DocumentUploadeds.Where(x => x.FileName == filename).FirstOrDefault();
                if (findDoc == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }

                db.DocumentUploadeds.Remove(findDoc);
                db.SaveChanges();
                var path = Path.Combine(Server.MapPath("~/Content/Files/"), findDoc.FileName);
                var Dirpath = Path.Combine(Server.MapPath("~/Content/Files/"), findDoc.FileName.Split('/')[0]);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                    System.IO.Directory.Delete(Dirpath, true);

                }
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public ActionResult GetContacts(int BuyerId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var contacts = db.CustomerContacts.OrderBy(a => a.CreatedOn).Where(x => x.BuyerId == BuyerId).ToList();
            return Json(new { data = contacts }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SaveContact(int id = 0)
        {
            //var v = db.LeadNotes.Where(a => a.Id == id).FirstOrDefault();
            return View("_PartialContact", new CustomerContacts());
        }
        [HttpPost]
        public ActionResult SaveContact(CustomerContacts contact)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                if (contact.Id > 0)
                {
                    //Edit part is not impletementd right now
                    var v = db.CustomerContacts.Where(a => a.Id == contact.Id).FirstOrDefault();
                    if (v != null)
                    {
                        v.ContactName = contact.ContactName;
                        v.ContactMobile = contact.ContactMobile;
                        v.ModifiedOn = contact.ModifiedOn;
                    }
                }
                else
                {
                    CustomerContacts contacts = new CustomerContacts();
                    contacts.BuyerId = contact.BuyerId;
                    contacts.ContactName = contact.ContactName;
                    contacts.ContactMobile = contact.ContactMobile;
                    contacts.CreatedOn = DateTime.Now;
                    contacts.ModifiedOn = DateTime.Now;
                    //Save
                    db.CustomerContacts.Add(contacts);
                }
                db.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult GetOpportunity(int BuyerId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var opportunities = db.Opportunities.OrderBy(a => a.CreatedOn).Where(x => x.BuyerId == BuyerId).ToList();
            return Json(new { data = opportunities }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SaveOpportunity(int id = 0)
        {
            //var v = db.LeadNotes.Where(a => a.Id == id).FirstOrDefault();
            return View("_PartialOpportunity", new Opportunity());
        }
        [HttpPost]
        public ActionResult SaveOpportunity(Opportunity opportunity)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                if (opportunity.Id > 0)
                {
                    //Edit part is not impletementd right now
                    var v = db.Opportunities.Where(a => a.Id == opportunity.Id).FirstOrDefault();
                    if (v != null)
                    {
                        v.OpportunityName = opportunity.OpportunityName;
                        v.ModifiedOn = DateTime.Now;
                    }
                }
                else
                {
                    Opportunity oppo = new Opportunity();
                    oppo.BuyerId = opportunity.BuyerId;
                    oppo.OpportunityName = opportunity.OpportunityName;
                    oppo.OpportunityStatus = Convert.ToInt32(Enum.OpportunityStatus.CompleteApplication);
                    oppo.CreatedOn = DateTime.Now;
                    oppo.ModifiedOn = DateTime.Now;
                    //Save
                    db.Opportunities.Add(oppo);
                }
                db.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult GetNotes(int BuyerId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var notes = db.LeadNotes.OrderBy(a => a.CreatedOn).Where(x => x.BuyerId == BuyerId).ToList();
            return Json(new { data = notes }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SaveNote(int id = 0)
        {
            //var v = db.LeadNotes.Where(a => a.Id == id).FirstOrDefault();
            return View("_PartialNote", new LeadNotes());
        }
    
        [HttpPost]
        public ActionResult SaveNoteView(NoteViewModel note)
        {
            bool status = false;
            if (ModelState.IsValid)
            {

HousingProject/Views/CRM/Contacts.cshtml
@model IEnumerable<HousingProject.Data.CustomerContacts>
@{
    ViewBag.Title = "Contacts";
    Layout = "~/Views/Shared/_UBoldAdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CRM</a></li>
                    <li class="breadcrumb-item active">Contacts</li>
                </ol>
            </div>
            <h4 class="page-title">Contacts</h4>
        </div>
    </div>
</div>
<!-- end page title -->


<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-4">
                        <form class="form-inline">
                            <div class="form-group mb-2">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" id="inputPassword2" placeholder="Search...">
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-8">
                        <div class="text-sm-right">
                            <button type="button" class="btn btn-success waves-effect waves-light mb-2 mr-1"><i class="mdi mdi-cog"></i></button>
                            @*<button type="button" class="btn btn-danger waves-effect waves-light mb-2" data-toggle="modal" data-target="#custom-modal">Add Contact</button>*@
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table table-centered table-nowrap table-hover mb-0">
                        <thead>
                            <tr>
                                <th>Basic Info</th>
                                <th>Phone</th>
                                <th>Email</th>
                                <th>Customer Name</th>
                                <th>Created Date</th>
                                <th style="width: 82px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var item in Model)
                            {
                            <tr>
                                <td class="table-user">
                                    <img src="~/UBold_v4.1.0/Admin/dist/assets/images/users/user-3.jpg" alt="table-user" class="mr-2 rounded-circle">
                                    <a href="@Url.Action("ProceedLead","Details",new {id=item.BuyerId,type="Customer",oppoId = 0 })" class="text-body font-weight-normal">@item.ContactName</a>
                                </td>
                                <td>
                                    @item.ContactMobile
                                </td>
                                <td>
                                    collier@jourrapide.com
                                </td>
                                <td>
                                    @item.buyers.BuyerName
                                </td>
                                <td>@item.CreatedOn</td>
                                <td>
                                    <a href="javascript:void(0);" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                    <a href="javascript:void(0);" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <ul class="pagination pagination-rounded justify-content-end mb-0 mt-2">
                    <li class="page-item">
                        <a class="page-link" href="javascript: void(0);" aria-label="Previous">
                            <span aria-hidden="true">«</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item active"><a class="page-link" href="javascript: void(0);">1</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">2</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">3</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">4</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">5</a></li>
                    <li class="page-item">
                        <a class="page-link" href="javascript: void(0);" aria-label="Next">
                            <span aria-hidden="true">»</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>

            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->

    
</div>
<!-- end row -->

HousingProject/Views/CRM/Customers.cshtml
@model IEnumerable<HousingProject.Data.Buyer_Detail>

@{
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_UBoldAdminLayout.cshtml";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CRM</a></li>
                    <li class="breadcrumb-item active">Customers</li>
                </ol>
            </div>
            <h4 class="page-title">Customers</h4>
        </div>
    </div>
</div>
<!-- end page title -->


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <div class="table-responsive">
                    <table class="table table-centered table-nowrap table-striped" id="products-datatable">
                        <thead>
                            <tr>
                                <th>Customer</th>
                                <th>Phone</th>
                                <th>Email</th>
                                <th>Location</th>
                                <th>Create Date</th>
                                <th>Status</th>
                                <th style="width: 85px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var item in Model)
                            {
                            <tr>
                                <td class="table-user">
                                    <img src="~/UBold_v4.1.0/Admin/dist/assets/images/users/user-6.jpg" alt="table-user" class="mr-2 rounded-circle">
                                    <a href="@Url.Action("ProceedLead","Details",new {id=item.BuyerId,type="Customer",oppoId = 0 })" class="text-body font-weight-normal">@item.BuyerName</a>
                                </td>
                                <td>
                                    @item.MobileNo
                                </td>
                                <td>
                                    @item.Email
                                </td>
                                <td>
                                    India
                                </td>
                                <td>
                                    @item.CreatedOn
                                </td>
                                <td>
                                    <span class="badge bg-soft-success text-success">Active</span>
                                </td>
                                <td>
                                    <a href="javascript:void(0);" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                    <a href="javascript:void(0);" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <ul class="pagination pagination-rounded justify-content-end mb-0">
                    <li class="page-item">
                        <a class="page-link" href="javascript: void(0);" aria-label="Previous">
                            <span aria-hidden="true">«</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item active"><a class="page-link" href="javascript: void(0);">1</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">2</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">3</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">4</a></li>
                    <li class="page-item"><a class="page-link" href="javascript: void(0);">5</a></li>
                    <li class="page-item">
                        <a class="page-link" href="javascript: void(0);" aria-label="Next">
                            <span aria-hidden="true">»</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>

            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
<!-- end row -->

HousingProject/Views/CRM/Index.cshtml
@model IEnumerable<HousingProject.Data.Opportunity>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UBoldAdminLayout.cshtml";
    var completeApplication = Model.Where(x => x.OpportunityStatus == Convert.ToInt32(HousingProject.Enum.OpportunityStatus.CompleteApplication)).Count();
    var uploadDocuments = Model.Where(x => x.OpportunityStatus == Convert.ToInt32(HousingProject.Enum.OpportunityStatus.UploadDocuments)).Count();
    var autologinBank = Model.Where(x => x.OpportunityStatus == Convert.ToInt32(HousingProject.Enum.OpportunityStatus.AutoLoginBank)).Count();
//    var checkStatus = Model.Where(x => x.OpportunityStatus == Convert.ToInt32(HousingProject.Enum.OpportunityStatus.AutoLoginBank)).Count();
    var disbursement = Model.Where(x => x.OpportunityStatus == Convert.ToInt32(HousingProject.Enum.OpportunityStatus.Disbursement)).Count();
}

<link href="~/UBold_v4.1.0/Admin/dist/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="~/UBold_v4.1.0/Admin/dist/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CRM</a></li>
                    <li class="breadcrumb-item active">Opportunities</li>
                </ol>
            </div>
            <h4 class="page-title">Opportunities</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-8 order-xl-1 order-2">
        <div class="card mb-2">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-8">
                        <form class="form-inline">
                            <div class="form-group">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" id="inputPassword2" placeholder="Search...">
                            </div>
                            <div class="form-group mx-sm-3">
                                <label for="status-select" class="mr-2">Sort By</label>
                                <select class="custom-select" id="status-select">
                                    <option selected="">All</option>
                                    <option value="1">Hot</option>
                                    <option value="2">Cold</option>
                                    <option value="3">In Progress</option>
                                    <option value="4">Lost</option>
                                    <option value="5">Won</option>
                                </select>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="text-lg-right mt-3 mt-lg-0">
                            <button type="button" class="btn btn-success waves-effect waves-light mr-1"><i class="mdi mdi-cog"></i></button>
                            @*<button type="button" class="btn btn-danger waves-effect waves-light" data-toggle="modal" data-target="#custom-modal"><i class="mdi mdi-plus-circle mr-1"></i> Add New</button>*@
                        </div>
                    </div><!-- end col-->
                </div> <!-- end row -->
            </div> <!-- end card-body-->
        </div> <!-- end card-->
        @*<div class="row" style="display:none" id="divMessage">
            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
                    <i class="mdi mdi-check-all mr-2"></i> Congratulations!! Customer has been added <strong>successfully</strong>!
                </div>
            </div>
        </div>*@
        @foreach (var item in Model)
        {
            <div class="card-box mb-2">
                <div class="row align-items-center">
                    <div class="col-sm-4">
                        <div class="media">
                            <img class="d-flex align-self-center mr-3 rounded-circle" src="~/UBold_v4.1.0/Admin/dist/assets/images/companies/amazon.png" alt="Generic placeholder image" height="64">
                            <div class="media-body">
                                <h4 class="mt-0 mb-2 font-16"><a href="@Url.Action("ProceedLead","Details",new {id = item.BuyerId, oppoId = item.Id, type="Opportunity" })">@item.OpportunityName</a></h4>
                                <p class="mb-1"><b>Buyer:</b> @item.Buyer.BuyerName</p>
                                <p class="mb-0"><b>Category:</b> Ecommerce</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <p class="mb-1 mt-3 mt-sm-0"><i class="mdi mdi-email mr-1"></i> @item.Buyer.Email</p>
                        <p class="mb-0"><i class="mdi mdi-phone-classic mr-1"></i> @item.Buyer.MobileNo</p>
                    </div>
                    <div class="col-sm-2">
                        <div class="text-center mt-3 mt-sm-0">
                            @if (item.OpportunityStatus == 1)
                            {
                                <div class="badge font-14 bg-soft-info text-info p-1">Complete Application</div>
                            }
                            else if (item.OpportunityStatus == 2)
                            {
                                <div class="badge font-14 bg-soft-primary text-primary p-1">Upload Documents</div>
                            }
                            else if (item.OpportunityStatus == 3)
                            {
                                <div class="badge font-14 bg-soft-warning text-warning p-1">Auto Login Bank</div>
                            }
                            else if (item.OpportunityStatus == 5)
                            {
                                <div class="badge font-14 bg-soft-success text-success p-1">Disbursement</div>
                            }
                            else
                            {
                                <div class="badge font-14 bg-soft-danger text-danger p-1">Rejected/Approved</div>
                            }
                        </div>
                    </div>
                </div> <!-- end row -->
            </div>
        }


        <div class="text-center my-4">
            <a href="javascript:void(0);" class="text-danger"><i class="mdi mdi-spin mdi-loading mr-1"></i> Load more </a>
        </div>

    </div> <!-- end col -->

    <div class="col-xl-4 order-xl-2 order-1">
        <div class="card-box" dir="ltr">
            <h4 class="header-title mb-3">Status Charts</h4>

            <div class="text-center">
                <div id="status-chart"></div>

                <p class="text-muted font-15 font-family-secondary mb-0 mt-3">
                    <span class="mx-2"><i class="mdi mdi-checkbox-blank-circle text-success"></i> Disbursed</span>
                    <span class="mx-2"><i class="mdi mdi-checkbox-blank-circle text-info"></i> Complete Application</span>
                    <span class="mx-2"><i class="mdi mdi-checkbox-blank-circle text-primary"></i> Upload Documents</span>
                    <span class="mx-2"><i class="mdi mdi-checkbox-blank-circle text-warning"></i> Auto Login Bank</span>
                    @*<span class="mx-2"><i class="mdi mdi-checkbox-blank-circle text-danger"></i> Lost</span>*@
                </p>
            </div>

        </div> <!-- end card-box-->
    </div> <!-- end col -->
</div>

@section Scripts{
    <!-- Sparkline chart js -->
    <script src="~/UBold_v4.1.0/Admin/dist/assets/libs/jquery-sparkline/jquery.sparkline.min.js"></script>

    <!-- Opportunities init js -->
    <script src="~/UBold_v4.1.0/Admin/dist/assets/js/pages/crm-opportunities.init.js"></script>
    <script src="~/UBold_v4.1.0/Admin/dist/assets/libs/sweetalert2/sweetalert2.min.js"></script>

    <!-- Sweet alert init js-->
    <script src="~/UBold_v4.1.0/Admin/dist/assets/js/pages/sweet-alerts.init.js"></script>
    <script>
        $(document).ready(function () {
            var t = ["#4fc6e1", "#1abc9c", "#f7b84b", "#6658dd"],
                c = $("#status-chart").data("colors"); c && (t = c.split(","));
            function e() {
                $("#status-chart").sparkline([@completeApplication, @disbursement, @autologinBank, @uploadDocuments], {
                    type: "pie", width: "220", height: "220", sliceColors: t
                })
            }
            var i; e(), $(window).resize(function (t) {
                clearTimeout(i), i = setTimeout(function () { e() }, 300)
            })
        });
    </script>
}