HousingProject/Controllers/DRMController.cs
using HousingProject.Data;
using HousingProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;
using System.Net;

namespace HousingProject.Controllers
{
    public class DRMController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            var list = db.PropertyListers.Where(x => x.IsConverted == false || x.IsConverted == null).ToList();
            return View(list);
        }

        [HttpPost]
        public ActionResult AddListerByAdmin(NewPropertyListerViewModel model)
        {
            var ListerDetails = db.PropertyListers.ToList();
            bool isValid = true;

            if (model.MobileNo != null || model.Email != null)
            {
                foreach (var item in ListerDetails)
                {
                    if (item.Email == model.Email)
                    {
                        isValid = false;
                    }
                    if (item.MobileNo == model.MobileNo)
                    {
                        isValid = false;
                    }
                }
            }

            if (!isValid)
            {
                TempData["Message"] = "Existing";
                return RedirectToAction("Index");
            }

            else if (ModelState.IsValid)
            {
                var lister = new PropertyLister
                {
                    Name = model.Name,
                    Email = model.Email,
                    MobileNo = model.MobileNo,
                    IsConverted = false,
                    ListerStatus = Convert.ToInt32(Enum.ListerStatus.New),
                    CreatedOn = DateTime.Now
                };

                db.PropertyListers.Add(lister);
                db.SaveChanges();
                TempData["Message"] = "New";
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }

        public ActionResult ProcessLead(int id)
        {
            var listers = db.PropertyListers.Include(x => x.listerDocuments).Include(x => x.listerNotes).Where(x => x.ListerId == id).FirstOrDefault();
            ManagerPropertyListerViewModel models = new ManagerPropertyListerViewModel();
            models.DocumentUpload = listers.listerDocuments.ToList();
            models.PropertyLister = listers;
            return View(models);
        }

        [HttpPost]
        public JsonResult SetStatus(int ListerId, int status)
        {
            var lister = db.PropertyListers.Find(ListerId);
            lister.ListerStatus = status;
            db.SaveChanges();
            return Json(new { status = "OK", currentStatus = status });
        }

        [HttpPost]
        public JsonResult SaveDetails(PropertyLister model)
        {
            var listerDetail = db.PropertyListers.Find(model.ListerId);
            listerDetail.FatherFirstName = model.FatherFirstName;
            listerDetail.FatherLastName = model.FatherLastName;
            listerDetail.Email = model.Email;
            listerDetail.DoB = model.DoB;
            listerDetail.MobileNo = model.MobileNo;
            db.SaveChanges();
            return Json(new { status = "OK", result = model });
        }

        [HttpPost]
        public ActionResult UploadLeadFiles()
        {
            //var file = Request.Files["FileUpload"];
            int listerId = Convert.ToInt32(Request.Form["ListerId"]);

            bool SavedSuccessfully = true;
            string fName = "";
            foreach (string filename in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[filename];
                var guid = Request.Form["Guid" + filename.Last()];
                fName = file.FileName;
                if (file != null && file.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Files/" + guid));
                    string pathstring = Path.Combine(path.ToString());

                    bool isexist = Directory.Exists(pathstring);
                    if (!isexist)
                    {
                        Directory.CreateDirectory(pathstring);
                    }
                    string uploadpath = string.Format("{0}\\{1}", pathstring, fName);
                    file.SaveAs(uploadpath);
                    var docDetail = new ListerDocumentsUploaded
                    {
                        ListerId = listerId,
                        FileName = guid + "/" + fName,
                    };
                    db.ListerDocumentsUploadeds.Add(docDetail);
                }
            }
            db.SaveChanges();
            if (SavedSuccessfully)
            {
                return Json(new { status = "OK" });
            }
            return Json(new { status = "False" });
        }

        [HttpPost]
        public JsonResult DeleteFile(string filename)
        {
            try
            {
                var findDoc = db.ListerDocumentsUploadeds.Where(x => x.FileName == filename).FirstOrDefault();
                if (findDoc == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }

                db.ListerDocumentsUploadeds.Remove(findDoc);
                db.SaveChanges();
                var path = Path.Combine(Server.MapPath("~/Content/Files/"), findDoc.FileName);
                var Dirpath = Path.Combine(Server.MapPath("~/Content/Files/"), findDoc.FileName.Split('/')[0]);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                    System.IO.Directory.Delete(Dirpath, true);
                }
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public ActionResult GetNotes(int listerId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var notes = db.ListerNotes.Where(x => x.ListerId == listerId).OrderBy(a => a.CreatedOn).ToList();
            return Json(new { data = notes }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SaveNote(int id = 0)
        {
            //var v = db.LeadNotes.Where(a => a.Id == id).FirstOrDefault();
            return View("_PartialNote", new ListerNotes());
        }

        [HttpPost]
        public ActionResult SaveNoteView(ListerNotes note)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                if (note.Id > 0)
                {
                    //Edit 
                    var v = db.ListerNotes.Where(a => a.Id == note.Id).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = note.Subject;
                        v.Description = note.Description;
                        v.UpdatedOn = note.UpdatedOn;
                    }
                }
                else
                {
                    ListerNotes notes = new ListerNotes();
                    notes.Id = note.Id;
                    notes.Subject = note.Subject;
                    notes.Description = note.Description;
                    notes.CreatedOn = DateTime.Now;
                    notes.UpdatedOn = DateTime.Now;
                    //Save
                    db.ListerNotes.Add(notes);
                }
                db.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }
    }
}

HousingProject/Views/DRM/Index.cshtml
@model IEnumerable<HousingProject.Data.PropertyLister>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UBoldAdminLayout.cshtml";
}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CRM</a></li>
                    <li class="breadcrumb-item active">Property Lister</li>
                </ol>
            </div>
            <h4 class="page-title">Property Lister</h4>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-lg-8 order-lg-1 order-2">
        <div class="card mb-2">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-4">
                        <form class="form-inline">
                            <div class="form-group">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" id="inputPassword2" placeholder="Search...">
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-8">
                        <div class="text-sm-right">
                            <button type="button" class="btn btn-success waves-effect waves-light mr-1"><i class="mdi mdi-cog"></i></button>
                            <button type="button" class="btn btn-danger waves-effect waves-light" data-toggle="modal" data-target="#custom-modal"><i class="mdi mdi-plus-circle mr-1"></i> Add New</button>

                        </div>
                    </div><!-- end col-->
                </div>

            </div> <!-- end card-body-->
        </div> <!-- end card-->

        <div class="row">
            <div class="col-sm-12">
                @if (ViewBag.Message != null)
                {
                    if (ViewBag.Message == "Existing")
                    {
                        <div class="alert alert-danger" role="alert">
                            <i class="mdi mdi-block-helper mr-2"></i> The Lister which you are trying to create
                            <strong>already exists</strong> in our database!
                        </div>

                    }
                    else
                    {
                        <div class="alert alert-success" role="alert">
                            <i class="mdi mdi-check-all mr-2"></i> Congratulations!! Your Property Lister has been <strong>generated</strong>!
                        </div>
                    }
                }
            </div>
        </div>

        @foreach (var item in Model)
        {
            <div class="card-box mb-2">
                <div class="row align-items-center">
                    <div class="col-sm-4">
                        <div class="media">
                            <img class="d-flex align-self-center mr-3 rounded-circle" src="~/UBold_v4.1.0/Admin/dist/assets/images/companies/amazon.png" alt="Generic placeholder image" height="64">
                            <div class="media-body">
                                <h4 class="mt-0 mb-2 font-16"><a href="@Url.Action("ProcessLead","DRM",new {id = item.ListerId })">@item.Name</a></h4>
                                <p class="mb-1"><b>Phone:</b> @item.MobileNo</p>
                                <p class="mb-0"><b>Email:</b> @item.Email</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="text-center my-3 my-sm-0">
                            <p class="mb-0 text-muted">@item.CreatedOn</p>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="text-center button-list">
                            <a href="javascript: void(0);" class="btn btn-xs btn-primary waves-effect waves-light">Assign</a>
                            <a href="javascript: void(0);" class="btn btn-xs btn-primary waves-effect waves-light">Call</a>
                            <a href="javascript: void(0);" class="btn btn-xs btn-primary waves-effect waves-light">Email</a>
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="text-sm-right text-center mt-2 mt-sm-0">
                            <a href="javascript:void(0);" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                            <a href="javascript:void(0);" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                        </div>
                    </div> <!-- end col-->
                </div> <!-- end row -->
            </div> <!-- end card-box-->
        }

        <div class="text-center my-4">
            <a href="javascript:void(0);" class="text-danger"><i class="mdi mdi-spin mdi-loading mr-1"></i> Load more </a>
        </div>

    </div> <!-- end col -->

    <div class="col-lg-4 order-lg-2 order-1">
        <div class="card-box">
            <h4 class="header-title mb-3">Leads Statics</h4>

            <div class="text-center" dir="ltr">
                <div class="row mt-2">
                    <div class="col-6">
                        <h3 data-plugin="counterup">1,284</h3>
                        <p class="text-muted font-13 mb-0 text-truncate">Leads Won</p>
                    </div>
                    <div class="col-6">
                        <h3 data-plugin="counterup">7,841</h3>
                        <p class="text-muted font-13 mb-0 text-truncate">Leads Lost</p>
                    </div>
                </div>

                <div id="leads-statics" style="height: 280px;" class="morris-chart" data-colors="#4a81d4,#e3eaef"></div>

                <p class="text-muted font-15 font-family-secondary mb-0 mt-3">
                    <span class="mx-2"><i class="mdi mdi-checkbox-blank-circle text-blue"></i> Leads Won</span>
                    <span class="mx-2"><i class="mdi mdi-checkbox-blank-circle text-muted"></i> Leads Lost</span>
                </p>
            </div>

        </div> <!-- end card-box-->
    </div> <!-- end col -->
</div>
<div class="modal fade" id="custom-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h4 class="modal-title" id="myCenterModalLabel">Add New Property Lister</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body p-4">
                @{
                    HousingProject.Models.NewPropertyListerViewModel model = new HousingProject.Models.NewPropertyListerViewModel();
                    @Html.Partial("_PartialLister", model);
                }
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<!-- end row -->

@section Scripts{

    <script src="~/UBold_v4.1.0/Admin/dist/assets/js/pages/crm-leads.init.js"></script>

    <!-- Sparkline chart js -->
    <script src="~/UBold_v4.1.0/Admin/dist/assets/libs/jquery-sparkline/jquery.sparkline.min.js"></script>

    <!-- Opportunities init js -->
    <script src="~/UBold_v4.1.0/Admin/dist/assets/js/pages/crm-opportunities.init.js"></script>
    <script src="~/UBold_v4.1.0/Admin/dist/assets/libs/sweetalert2/sweetalert2.min.js"></script>

    <!-- Sweet alert init js-->
    <script src="~/UBold_v4.1.0/Admin/dist/assets/js/pages/sweet-alerts.init.js"></script>
}

HousingProject/Views/DRM/_PartialLister.cshtml
@model HousingProject.Models.NewPropertyListerViewModel

@using (Html.BeginForm("AddListerByAdmin", "DRM", FormMethod.Post))
{
    <div class="form-group">
        <label for="name">User Name</label>
         @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @required = "required", placeholder = "Enter user name" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", type = "email", @required = "required", placeholder = "Enter emaill address" })
       
    </div>
    <div class="form-group">
        <label for="position">Phone</label>
        @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control", type = "number", @required = "required", placeholder = "Enter phone number" })
    </div>


    <div class="text-right">
        <button type="submit" class="btn btn-success waves-effect waves-light">Save</button>
        <button type="button" class="btn btn-danger waves-effect waves-light" data-dismiss="modal">Continue</button>
    </div>
}

HousingProject/Views/DRM/_PartialNote.cshtml
@model HousingProject.Data.ListerNotes
@{ 
    Layout = null;
}

    @Html.HiddenFor(model => model.ListerId)
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        <label for="name">Subject</label>
        @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @required = "required", placeholder = "Enter Subject" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Description</label>
        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @required = "required", rows = 5 })

    </div>


    <div class="text-right">
        <button type="button" class="btn btn-success waves-effect waves-light" id="btnSaveNote">Save</button>
        <button type="button" class="btn btn-danger waves-effect waves-light" data-dismiss="modal">Cancel</button>
    </div>