HousingProject/Controllers/AdminController.cs
using HousingProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HousingProject.Data;
using System.Net;
using System.IO;
using System.Data.Entity;
using System.Threading.Tasks;
using LinqToExcel;

namespace HousingProject.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public string GetUserId()
        {
            var userId = Session["UserId"].ToString();
            return userId;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Profile()
        {
            return View();
        }

        public ActionResult Leads()
        {
            ViewBag.Message = TempData["Message"];
            var list = db.BuyerDetails.Include("ManagerDetail").Where(x => x.IsConverted == false || x.IsConverted == null).ToList();
            return View(list);
        }

        [HttpPost]
        public ActionResult AddLeadByAdmin(NewBuyerViewModel model)
        {
            var userDetails = db.BuyerDetails.ToList();
            bool isValid = true;

            if (model.MobileNo != null || model.Email != null)
            {
                foreach (var item in userDetails)
                {
                    if (item.Email == model.Email)
                    {
                        isValid = false;
                    }
                    if (item.MobileNo == model.MobileNo)
                    {
                        isValid = false;
                    }
                }
            }

            if (!isValid)
            {
                TempData["Message"] = "Existing";
                return RedirectToAction("Leads");
            }

            else if (ModelState.IsValid)
            {
                var buyer = new Buyer_Detail
                {
                    BuyerName = model.BuyerName,
                    Email = model.Email,
                    MobileNo = model.MobileNo,
                    IsAlreadyCustomer = false,
                    LeadStatusId = Convert.ToInt32(Enum.LeadStatus.New),
                    CreatedOn = DateTime.Now
                };

                db.BuyerDetails.Add(buyer);
                db.SaveChanges();
                TempData["Message"] = "New";
                return RedirectToAction("Leads");

            }
            return RedirectToAction("Leads");
        }
        
        public ActionResult DealerLeads()
        {
            var list = db.BuyerDetails.Include("ManagerDetail").ToList();
            return View(list);
        }
        public ActionResult Dealer()
        {
            var dealerDetail = db.Users.Where(x => x.UserType == 5).ToList();

            List<DealerToManagerViewModel> relation = new List<DealerToManagerViewModel>();

            var managerDetails = (from m in db.DealerToManagerRelations
                                  join d in db.Users on m.ManagerId equals d.Id
                                  select new
                                  {
                                      m.DealerId,
                                      m.ManagerId,
                                      m.ManagerDetails.FirstName
                                  }).ToList();
            foreach (var item in managerDetails)
            {
                relation.Add(new DealerToManagerViewModel
                {
                    DealerId = item.DealerId,
                    ManagerId = item.ManagerId,
                    ManagerName = item.FirstName
                });
            }
            ViewBag.ManagerDetails = relation;

            return View(dealerDetail);
        }
        public ActionResult Customers()
        {
            var customers = db.BuyerDetails.Where(x => x.LeadStatusId == Convert.ToInt32(Enum.LeadStatus.Converted) && x.IsConverted == true).ToList();
            return View(customers);
        }

        //[HttpPost]
        //public JsonResult AddCustomer(int Id)
        //{
        //    var leadDetails = db.BuyerDetails.Find(Id);
        //    if (leadDetails == null)
        //    {
        //        Response.StatusCode = (int)HttpStatusCode.NotFound;
        //        return Json(new { Result = "Error" });
        //    }

        //    var customer = new Customer
        //    {
        //        BuyerId = leadDetails.BuyerId,
        //        Name = leadDetails.BuyerName,
        //        MobileNo = leadDetails.MobileNo,
        //        Email = leadDetails.Email
        //    };
        //    db.Customers.Add(customer);
        //    leadDetails.IsAlreadyCustomer = true;

        //    db.SaveChanges();
        //    return Json(new { Result = "OK" });
        //}

        public ActionResult ViewCustomer()
        {
            return View();
        }

        public ActionResult ProcessLead(int id)
        {
            var leads = db.BuyerDetails.Include(x => x.DocumentUploadeds).Where(x => x.BuyerId == id).FirstOrDefault();
            ManageBuyerViewModel manager = new ManageBuyerViewModel();
            manager.BuyerDetail.BuyerId = leads.BuyerId;
            manager.BuyerDetail.BuyerName = leads.BuyerName;
            manager.BuyerDetail.Email = leads.Email;
            manager.BuyerDetail.MobileNo = leads.MobileNo;
            manager.BuyerDetail.DateOfBirth = leads.dob;
            manager.BuyerDetail.FatherFirstName = leads.FatherFirstName;
            manager.BuyerDetail.FatherMiddleName = leads.FatherMiddleName;
            manager.BuyerDetail.LeadStatusId = leads.LeadStatusId;

            manager.FileUpload = leads.DocumentUploadeds.ToList();
            return View(manager);
        }

        [HttpPost]
        public JsonResult SetStatus(int BuyerId, int status)
        {
            var buyer = db.BuyerDetails.Find(BuyerId);
            buyer.LeadStatusId = status;
            db.SaveChanges();
            return Json(new { status = "OK", currentStatus = status });
        }

        [HttpPost]
        public JsonResult SaveDetails(BuyerDetailViewModel model)
        {
            var buyerDetail = db.BuyerDetails.Find(model.BuyerId);
            buyerDetail.FatherFirstName = model.FatherFirstName;
            buyerDetail.FatherMiddleName = model.FatherMiddleName;
            buyerDetail.Email = model.Email;
            buyerDetail.dob = model.DateOfBirth;
            buyerDetail.MobileNo = model.MobileNo;
            db.SaveChanges();
            return Json(new { status = "OK", result = model });
        }

        [HttpPost]
        public ActionResult UploadLeadFiles()
        {
            //var file = Request.Files["FileUpload"];
            int BuyerId = Convert.ToInt32(Request.Form["BuyerId"]);
            
            bool SavedSuccessfully = true;
            string fName = "";
            foreach (string filename in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[filename];
                var guid = Request.Form["Guid" + filename.Last()];
                fName = file.FileName;
                if (file != null && file.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Files/"+guid));
                    string pathstring = Path.Combine(path.ToString());
                    
                    bool isexist = Directory.Exists(pathstring);
                    if (!isexist)
                    {
                        Directory.CreateDirectory(pathstring);
                    }
                    string uploadpath = string.Format("{0}\\{1}", pathstring, fName);
                    file.SaveAs(uploadpath);
                    var docDetail = new DocumentUploaded
                    {
                        BuyerId = BuyerId,
                        FileName = guid+"/"+fName,
                    };
                    db.DocumentUploadeds.Add(docDetail);
                }
            }
            db.SaveChanges();
            if (SavedSuccessfully)
            {
                return Json(new { status = "OK" });
            }
            return Json(new { status = "False" });
        }

        [HttpPost]
        public JsonResult DeleteFile(string filename)
        {
            try
            {
                var findDoc = db.DocumentUploadeds.Where(x => x.FileName == filename).FirstOrDefault();
                if (findDoc == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }

                db.DocumentUploadeds.Remove(findDoc);
                db.SaveChanges();
                var path = Path.Combine(Server.MapPath("~/Content/Files/"), findDoc.FileName);
                var Dirpath = Path.Combine(Server.MapPath("~/Content/Files/"), findDoc.FileName.Split('/')[0]);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                    System.IO.Directory.Delete(Dirpath,true);
                    
                }
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        //Below code is used for upload file using different js
        //[HttpPost]
        //public ActionResult UploadFile()
        //{
        //    bool SavedSuccessfully = true;
        //    string fName = "";
        //    foreach (string filename in Request.Files)
        //    {
        //        HttpPostedFileBase file = Request.Files[filename];
        //        fName = file.FileName;
        //        if (file != null && file.ContentLength > 0)
        //        {
        //            var path = Path.Combine(Server.MapPath("~/Content/Files"));
        //            string pathstring = Path.Combine(path.ToString());

HousingProject/Controllers/DealerController.cs
using HousingProject.Data;
using HousingProject.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HousingProject.Controllers
{
    [Authorize]
    public class DealerController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public string GetUserId()
        {
            var userId = Session["UserId"].ToString();
            return userId;
        }
        // GET: Dealer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Profile()
        {
            return View();
        }
        public ActionResult Lead()
        {
            string userId = Session["UserId"].ToString(); ;
            ViewBag.ManagerAssigned = db.DealerToManagerRelations.Include("ManagerDetails").Where(x => x.DealerId == userId).FirstOrDefault();
            ViewBag.Message = TempData["Message"];
            var model = db.DealerLeadRelations.Include("ManagerDetails").Where(x => x.LeadCreatedBy == userId).ToList();
            foreach(var item in model)
            {
                item.LeadCreatedOnDate = String.Format("{0:MMMM}", item.LeadCreatedOn);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddLead(NewBuyerViewModel model)
        {
            var currentUser = GetUserId();
            var userDetails = db.BuyerDetails.ToList();
            bool isValid = true;

            if (model.MobileNo != null || model.Email!= null)
            {
                foreach (var item in userDetails)
                {
                    if (item.Email == model.Email)
                    {
                        isValid = false;
                    }
                    if (item.MobileNo == model.MobileNo)
                    {
                        isValid = false;
                    }
                }
            }

            if (!isValid)
            {
                var getBuyerDetails = db.BuyerDetails.Include("ManagerDetail").Where(x => x.MobileNo == model.MobileNo || x.Email == model.Email).FirstOrDefault();

                var addLeadToDealer = new DealerToLeadRelation
                {
                    BuyerId = getBuyerDetails.BuyerId,
                    PhoneNo = getBuyerDetails.MobileNo,
                    BuyerName = getBuyerDetails.BuyerName,
                    WillGetPayout = false,
                    LeadCreatedOn = DateTime.Now,
                    LeadStatus = getBuyerDetails.currenStatus,
                    LeadVerifiedBy = GetUserId()
                };
                if (getBuyerDetails.ManagerDetail != null)
                {
                    addLeadToDealer.AssignedManager = getBuyerDetails.ManagerDetail.Id;
                }

                var DealerToLeadDetails = db.DealerLeadRelations.Where(x => x.BuyerId == getBuyerDetails.BuyerId).FirstOrDefault();
                if (DealerToLeadDetails.LeadVerifiedBy != currentUser)
                {
                    db.DealerLeadRelations.Add(addLeadToDealer);
                }
                db.SaveChanges();

                TempData["Message"] = "Existing";

                return RedirectToAction("Lead");
            }

            if (ModelState.IsValid)
            {
                var currentDealer = GetUserId();
                var getManager = db.DealerToManagerRelations.Where(x => x.DealerId == currentDealer).Select(x => x.ManagerId).FirstOrDefault();

                var buyer = new Buyer_Detail
                {
                    BuyerName = model.BuyerName,
                    Email = model.Email,
                    MobileNo = model.MobileNo,
                    ManagerAssigned = getManager,
                    LeadIncomingFrom = HousingProject.Enum.LeadComingFrom.Dealer.ToString(),
                    IsAlreadyCustomer = false,
                    LeadStatusId = Convert.ToInt32(Enum.LeadStatus.New),
                    LeadCreatedBy = GetUserId(),
                    CreatedOn = DateTime.Now
                };


                db.BuyerDetails.Add(buyer);
                db.SaveChanges();

                var buyerRelation = new BuyerRelation
                {
                    BuyerId = buyer.BuyerId,
                    ManagerId = getManager,
                    UpdatedOn = DateTime.Now

                };

                var addLeadToBuyer = new DealerToLeadRelation
                {
                    BuyerId = buyer.BuyerId,
                    BuyerName = buyer.BuyerName,
                    WillGetPayout = true,
                    LeadCreatedOn = DateTime.Now,
                    PhoneNo = buyer.MobileNo,
                    LeadStatus = buyer.currenStatus,
                    AssignedManager = getManager,
                    LeadCreatedBy = GetUserId()
                };

                db.BuyerRelation.Add(buyerRelation);
                db.DealerLeadRelations.Add(addLeadToBuyer);
                db.SaveChanges();
                TempData["Message"] = "New";
                return RedirectToAction("Lead");

            }
            return RedirectToAction("Index");
        }
       
    }
}

HousingProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.Role == 5)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    }
                    else if (ViewBag.Role == 0)
                    {
                        <li>@Html.ActionLink("Super User", "Index", "Home")</li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HousingProject/Views/Shared/_LeftLoginPartial.cshtml
@using Microsoft.AspNet.Identity

    @if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()
            <div class="user-box text-center">
                    <img src="~/UBold_v4.1.0/Admin/dist/assets/images/users/user-6.jpg" alt="user-img" title="Mat Helme"
                         class="rounded-circle avatar-md">
                    <div class="dropdown">
                        <a href="javascript: void(0);" class="text-dark font-weight-normal dropdown-toggle h5 mt-2 mb-1 d-block"
                           data-toggle="dropdown">@User.Identity.GetUserName()</a>
                        <div class="dropdown-menu user-pro-dropdown">

                            <!-- item-->
                            <a href="@Url.Action("Profile","Admin")" class="dropdown-item notify-item">
                                <i class="fe-user mr-1"></i>
                                <span>My Account</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="fe-settings mr-1"></i>
                                <span>Settings</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="fe-lock mr-1"></i>
                                <span>Lock Screen</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:document.getElementById('logoutForm').submit();" class="dropdown-item notify-item">
                                <i class="fe-log-out mr-1"></i>
                                <span>Logout</span>
                            </a>

                        </div>
                    </div>
                    <p class="text-muted">Admin Head</p>
                </div>

        }
    }

HousingProject/Views/Shared/_LeftLoginPartialUser.cshtml
@using Microsoft.AspNet.Identity

    @if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()
            <div class="user-box text-center">
                    <img src="~/UBold_v4.1.0/Admin/dist/assets/images/users/user-6.jpg" alt="user-img" title="Mat Helme"
                         class="rounded-circle avatar-md">
                    <div class="dropdown">
                        <a href="javascript: void(0);" class="text-dark font-weight-normal dropdown-toggle h5 mt-2 mb-1 d-block"
                           data-toggle="dropdown">@User.Identity.GetUserName()</a>
                        <div class="dropdown-menu user-pro-dropdown">

                            <!-- item-->
                            <a href="@Url.Action("Profile","Dealer")" class="dropdown-item notify-item">
                                <i class="fe-user mr-1"></i>
                                <span>My Account</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="fe-settings mr-1"></i>
                                <span>Settings</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="fe-lock mr-1"></i>
                                <span>Lock Screen</span>
                            </a>

                            <!-- item-->
                            <a href="javascript:document.getElementById('logoutForm').submit();" class="dropdown-item notify-item">
                                <i class="fe-log-out mr-1"></i>
                                <span>Logout</span>
                            </a>

                        </div>
                    </div>
                    <p class="text-muted">Admin Head</p>
                </div>

        }
    }

HousingProject/Views/Shared/_LoginPartialUser.cshtml
@using Microsoft.AspNet.Identity

<li class="dropdown notification-list topbar-dropdown">
    @if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <img src="~/UBold_v4.1.0/Admin/dist/assets/images/users/user-6.jpg" alt="user-image" class="rounded-circle">
                <span class="pro-user-name ml-1">
                    @User.Identity.GetUserName() <i class="mdi mdi-chevron-down"></i>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>

                <!-- item-->
                <a href="@Url.Action("Profile","Dealer")" class="dropdown-item notify-item">
                    <i class="fe-user"></i>
                    <span>My Account</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="fe-settings"></i>
                    <span>Settings</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="fe-lock"></i>
                    <span>Lock Screen</span>
                </a>

                <div class="dropdown-divider"></div>

                <!-- item-->
                <a href="javascript:document.getElementById('logoutForm').submit();" class="dropdown-item notify-item">
                    <i class="fe-log-out"></i>
                    <span>Logout</span>
                </a>

            </div>
            
        }
    }

</li>